name: GitHubPipelineWithChange


on:
  workflow_dispatch:
    

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Set Node.js 12.x
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 12.x

    # - name: Install dependencies
    #   run: npm ci

    # - name: Compile
    #   run: npm run build

  integrationTest:
      #if: github.event.pull_request.merged == true
      name: Integration Tests
      needs: Build
      runs-on: ubuntu-latest
      steps:
          - name: ServiceNow DevOps Register Artifact
          # You may pin to the exact commit or the version.
          # uses: ServiceNow/servicenow-devops-register-artifact@6312802fd9eecd4a57b13216e968b8cae4ff6fe4
            uses: ServiceNow/servicenow-devops-register-artifact@main
            with:
                # Devops Integration User Name
                devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
                # Devops Integration User Password
                devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
                # ServiceNow Instance URL
                instance-url: ${{ secrets.SN_INSTANCE_URL }}
                # Orchestration Tool Id
                tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
                # Display Name of the Job
                job-name: 'Integration Tests'
                # Github Context
                context-github: ${{ toJSON(github) }}
                # List of Artifacts to be registered
                artifacts: '[
                        {
                            "name": "app-devops.jar",
                            "version": "1.${{ github.run_number }}",
                            "semanticVersion": "1.${{ github.run_number }}.0",
                            "repositoryName": "${{ github.repository }}"
                        },
                        {
                            "name": "app-devops-integrations.jar",
                            "version": "1.${{ github.run_number }}",
                            "semanticVersion": "1.${{ github.run_number }}.0",
                            "repositoryName": "${{ github.repository }}"
                        },
                        {
                            "name": "app-devops-workspace.jar",
                            "version": "1.${{ github.run_number }}",
                            "semanticVersion": "1.${{ github.run_number }}.0",
                            "repositoryName": "${{ github.repository }}"
                        }
                    ]'

    
  # changeApproval:
  #   name: ServiceNow Change Approval
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:     

  #     - name: ServiceNow Change Approval
  #       uses: ServiceNow/servicenow-devops-change@main
  #       with:
  #         #devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
  #         #devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
  #         devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
  #         instance-url: ${{ secrets.SN_INSTANCE_URL }}
  #         tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
  #         context-github: ${{ toJSON(github) }}
  #         job-name: 'ServiceNow Change Approval'
  #         change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
  #         interval: '100'
  #         timeout: '3600'
  #         # changeCreationTimeOut: '3600'
  #         # abortOnChangeCreationFailure: true
  #         # abortOnChangeStepTimeout: true

